/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Bootloadable_1.h>
#include <Clock_1.h>
#include <TaskISR.h>
#include <UART_1.h>
#include <UART_1_SPI_UART.h>
#include <UART_1_PINS.h>
#include <UART_1_SPI_UART_PVT.h>
#include <UART_1_PVT.h>
#include <UART_1_BOOT.h>
#include <TaskTimer.h>
#include <SW1.h>
#include <SW1_aliases.h>
#include <BootISR.h>
#include <NavLightPWM.h>
#include <Clock_2.h>
#include <NavLR.h>
#include <NavLR_aliases.h>
#include <NavB.h>
#include <NavB_aliases.h>
#include <Strobes.h>
#include <Strobes_aliases.h>
#include <Collis.h>
#include <Collis_aliases.h>
#include <Ldg.h>
#include <Ldg_aliases.h>
#include <SpareLight.h>
#include <SpareLight_aliases.h>
#include <OnBoardLED.h>
#include <OnBoardLED_aliases.h>
#include <PPMCounter.h>
#include <Clock_3.h>
#include <PPMISR.h>
#include <PPMRstISR.h>
#include <PPMIN.h>
#include <PPMIN_aliases.h>
#include <TelemUART.h>
#include <ServoTimer.h>
#include <ServoISR.h>
#include <Out_Mot_Pin.h>
#include <Out_Mot_Pin_aliases.h>
#include <Out_Ail1_Pin.h>
#include <Out_Ail1_Pin_aliases.h>
#include <Out_Ail2_Pin.h>
#include <Out_Ail2_Pin_aliases.h>
#include <Out_Ele1_Pin.h>
#include <Out_Ele1_Pin_aliases.h>
#include <Out_Ele2_Pin.h>
#include <Out_Ele2_Pin_aliases.h>
#include <Out_Rud_Pin.h>
#include <Out_Rud_Pin_aliases.h>
#include <Out_Fl1_Pin.h>
#include <Out_Fl1_Pin_aliases.h>
#include <Out_Fl2_Pin.h>
#include <Out_Fl2_Pin_aliases.h>
#include <Out_Ge1_Pin.h>
#include <Out_Ge1_Pin_aliases.h>
#include <Out_Ge2_Pin.h>
#include <Out_Ge2_Pin_aliases.h>
#include <Out_Ge3_Pin.h>
#include <Out_Ge3_Pin_aliases.h>
#include <Out_Sp1_Pin.h>
#include <Out_Sp1_Pin_aliases.h>
#include <Out_Sp2_Pin.h>
#include <Out_Sp2_Pin_aliases.h>
#include <I2CM.h>
#include <I2CM_I2C.h>
#include <I2CM_PINS.h>
#include <I2CM_I2C_PVT.h>
#include <I2CM_PVT.h>
#include <I2CM_BOOT.h>
#include <ADC.h>
#include <In_Speed.h>
#include <In_Speed_aliases.h>
#include <UART_1_SCBCLK.h>
#include <UART_1_tx.h>
#include <UART_1_tx_aliases.h>
#include <UART_1_rx.h>
#include <UART_1_rx_aliases.h>
#include <TelemUART_IntClock.h>
#include <I2CM_SCBCLK.h>
#include <I2CM_sda.h>
#include <I2CM_sda_aliases.h>
#include <I2CM_scl.h>
#include <I2CM_scl_aliases.h>
#include <I2CM_SCB_IRQ.h>
#include <ADC_IRQ.h>
#include <ADC_intClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

